### PR TITLE
bug fix and add multi-light example

### PR DESCRIPTION
**Pull request by karenpeng**

### CODE REVIEW

**Comment by indefinit** [comment]
I'm 99% ready to merge this into master but I noticed we don't have any examples in immediateMode of beginShape endShape anymore.  Do you think we should add another example demonstrating that functionality?  Could likely be a different PR but just wanted to note it here.

**Comment by indefinit** [comment]
@karenpeng  One more thing.  What are your thoughts on replacing mouse drag functionality in the examples with mouse move instead?  Reasoning is that camera's orbit control isn't quite ready for primetime (though it's getting close!) and I think it will be less confusing to users if there are fewer instructions.  I'll take a stab at this and push here as example for us to discuss.

**Comment by karenpeng** [comment]
There's still works to do in immediateMode, for example, `strokeWidth`, and `point`, I want to make examples after they are fixed.
I agree on you about making `orbitControl` less effort to use.  But mouse move sometimes would be annoying. How about making it takes an argument of either `"drag"` or `"move"`? Will that be too much?

**Comment by indefinit** [comment]
Technically orbit control should be controlling the view matrix and not altering the model matrix- I think it needs a little more planning to get the implementation perfect, and in the short term if our goal is just to rotate objects to show their geometries in perspective bs ortho, we should just use rotate with as little user instructions as possible.  Take a look at my latest changes where I removed orbit control from the examples.  I already PRed the upstream repo and those changes have been merged into master.  

Re: stroke and point, I agree with you we should put efforts there to get those fixed and PR again for completion.  I started looking at point last weekend but didn't find a quick fix so put it aside. Will take a look again this weekend.  I'd love to be able to do point sprites for particle systems.

**Comment by indefinit** [comment]
Re: strokeWidth, have a look at this article: http://www.goodboydigital.com/pixi-webgl-primitives/

It seems if we want to adjust lineWidth we should really be drawing triangulated quads.  The math behind this isn't that bad because there's a lot of precedence, but it's still non-trivial and would require a refactor of our existing line function- maybe wrapping the approach of immediate mode...

**Pull request merged**
