### PR TITLE
lighting improvement

### PR DESCRIPTION
**Pull request by karenpeng**
- three kinds of light supported: `ambientLight` `directionalLight` `pointLight`
- all of these three kinds of lights support multiple numbers

### CODE REVIEW

**Comment by indefinit** [comment]
Fantastic!  Some notes on the changes (some admittedly nit-picky so take with a grain of salt)

File: light.js 
- `_normalizeColor` function.  Since we use this function a lot in webgl, maybe it's better to refactor into the Renderer3D scope (or maybe it's more appropriate inside color_utils.js).
- Is there a better way to store light count than as a member of the graphics context?  having light counts live inside an object like `this._graphics.lights = { ambientLightCount=0, directionalLightCount=0} ...`
  is probably prettier, with the tradeoff of being slightly more verbose.
- line 101:  I wonder if we can accommodate for type checking and/or "friendly error messages" here.  It would be great to pass vectors, color objects, etc, in addition to just the component parameters but doing so makes the existing implementation more error prone.
  -`uniform4f`& general comment about decimal places.  If it's a float var (especially inside shaders), let's try to keep it consistent and always have decimal points and 0s.  eg. float alpha=1.0, not float alpha 1.  End requisite nitpicky style comment.
- `RESOLUTION` variable.  I think I understand why you're doing this but as a variable, the number 1 reads better to me for this purpose than 1000.  For example, if the resolution is 1, then we just multiply it by 1000 inside the function.  I think it also needs a short explanation in an inline comment.  Also, is there ever a situation where we override the RESOLUTION variable?

File Renderer3D:
- Line 179: this is admittedly a giant function, and I wonder if it would make it cleaner if we just pull this section out and refactor as its own function.

General uniform naming convention.  If we call the js variable MVMatrix, I think we should probably keep consistency inside the uniform by renaming uModelviewMatrix to uModelViewMatrix

**Comment by karenpeng** [comment]
Thanks for the suggestions. 
- `normalize` now is a method of `p5.Color`
- I leave the `ambientLightCount` as it was because I'm still working on the shader.
- Nope the `RESOLUTION` is never overrode, I'm not sure I understand what you mean, do you mean to have a function manipulating value of it?
  `RESOLUTION` might be a bad name here, what it does is shrinking user input value, so as to fit into  the coordinate system.  1000 is hard coded here, there must be a better way to do it.
- naming is redone.

**Comment by karenpeng** [comment]
A new update:
 <b> camera </b>
- three functions are added in camera.js: `camera`, `perspective`, `ortho`
- good part is user has control to the camera, also it solves the problem with ratio distortion
- bad part is that it might be to complicated for user to set camera (like what i did in the example sketches)

Still figuring out how to detect if the user didn't set the camera so that we could have it set as default for them.

**Comment by indefinit** [comment]
Looks great!  Re: ambientLight example, I think it's a little too subtle.  What do you think if we had a toggle so users can see the difference between ambientLight on and off?

Also, does this PR include bug fixes for Issue #865?

**Comment by karenpeng** [comment]
That's a great idea too! Will go over all the examples again after the camera is refined(so that it's not mandatory).
Yes, it's fixed, see commit ad84db9.

**Comment by karenpeng** [comment]
btw, i'm going to write a shader with both texture and lighting supported after your texture loading function is refined.

**Pull request merged**
